### ISSUE TITLE
jwt module is missing on SPS 6.10

### ISSUE THREAD

**Issue by ghost** [OneIdentity/safeguard-sessions-plugin-pingid#5]
Hi,

The plugin fails with the following error on SPS v6.10:

Plugin(aa/SPS_PingID_Plugin/main.py): ModuleNotFoundError: No module named 'jwt'
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "/opt/plugin-sdk/lib/python3.8/site-packages/safeguard/sessions/plugin_impl/pluginwrapper.py", line 30, in load_source
Plugin(aa/SPS_PingID_Plugin/main.py): module_spec.loader.exec_module(module)
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "<frozen importlib._bootstrap_external>", line 783, in exec_module
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "/opt/scb/var/plugins/aa/SPS_PingID_Plugin/main.py", line 3, in <module>
Plugin(aa/SPS_PingID_Plugin/main.py): from lib.plugin import Plugin
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "/opt/scb/var/plugins/aa/SPS_PingID_Plugin/lib/plugin.py", line 8, in <module>
Plugin(aa/SPS_PingID_Plugin/main.py): from .pingid import Client, ResponseError
Plugin(aa/SPS_PingID_Plugin/main.py):
Plugin(aa/SPS_PingID_Plugin/main.py): File "/opt/scb/var/plugins/aa/SPS_PingID_Plugin/lib/pingid.py", line 9, in <module>

Thanks!
Viktor

**Comment by gorosz** [comment]
The issue was packaging related, created a new release and published it here. Tested plugin is working as intended
